name: Go

on:
  push:
    branches: [ musl-go ]
  pull_request:
    branches: [ musl-go ]

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [macos-11, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v2
